vim /etc/keepalived/keepalived.conf
global_defs {
   router_id NGINX_MASTER
   enable_script_security
   script_user root
}

# 业务健康检测规则
vrrp_script check_nginx_web {
    script "/etc/keepalived/check_nginx_http.sh"
    interval 2        # 2秒检测一次
    init_fail         # 初始化默认故障状态
    fall 2            # 连续2次失败判定故障
    rise 2            # 连续2次恢复判定正常
}

vrrp_instance VI_1 {
    state BACKUP
    interface ens33
    virtual_router_id 51
    priority 100      # 主节点优先级更高
    advert_int 1
    mcast_src_ip 192.168.1.10

    # 绑定健康检测脚本
    track_script {
        check_nginx_web
    }

    nopreempt         # 开启防抢占，避免正常切换
    authentication {
        auth_type PASS
        auth_pass 123456
    }
    virtual_ipaddress {
        192.168.1.100/24  # 虚拟漂移IP
    }
}
