server {
    listen 127.0.0.1:8088;
    listen 192.168.81.133:8088;
    server_name localhost;
    location /check_status {
        check_status; # 展示集群健康状态
        allow 127.0.0.1;
        allow 192.168.81.0/24;
        allow 192.168.3.0/24;
        deny all;
    }
}
