user www-data;

# 自动适配服务器CPU核心数，启动对应数量工作进程，最大化利用多核性能
worker_processes auto;

# 记录Nginx主进程PID文件路径，用于服务启停、进程管理
pid logs/nginx.pid;

# 全局错误日志路径，记录服务启动、配置、运行级故障
error_log /data/logs/nginx/error.log;


# 事件模块配置：控制并发连接模型
events {
        # 单工作进程最大支持51200并发连接，提升高并发承载能力
        worker_connections 51200;
        # multi_accept on; 开启后可一次性接收多个新连接，高并发场景建议开启
}

# HTTP全局模块：管控所有HTTP/HTTPS站点通用规则
http {
        # 开启高效sendfile文件传输机制，提升静态文件传输效率
        sendfile on;
        # 合并TCP数据包，减少网络IO次数，降低网络开销
        tcp_nopush on;

        # 优化MIME类型哈希表缓存，提升文件类型匹配速度
        types_hash_max_size 2048;

        # 隐藏Nginx版本号，防止针对性版本漏洞攻击，提升安全性
        server_tokens off;

        # 加载系统默认MIME类型，识别网页、图片、脚本等文件类型
        include mime.types;
        # 未知文件默认以二进制流方式输出下载
        default_type application/octet-stream;
	# 自定义日志格式main
	 log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" $request_time $upstream_response_time';

        # ==================== SSL全局安全配置 ====================
        # 兼容主流TLS加密协议，禁用老旧不安全协议，保障HTTPS安全
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; 
        # 优先使用服务器加密套件，规避客户端弱加密漏洞
        ssl_prefer_server_ciphers on;


        # 全局默认访问日志存储路径
        access_log /data/logs/nginx/access.log;

        # ==================== Gzip压缩配置 ====================
        # 开启全站Gzip压缩，压缩网页、静态资源，减小传输体积、提升访问速度
        gzip on;
         # 客户端超时优化，释放无效空闲连接
         keepalive_timeout 60;      # 长连接超时60秒
          client_header_timeout 10;  # 请求头超时
          client_body_timeout 10;    # 请求体超时
           send_timeout 10;           # 响应发送超时
        # 加载conf.d目录下所有自定义配置文件
        include conf.d/*.conf;
}
